-- Touch-up migration (run once in Supabase SQL Editor)

ALTER TABLE restaurant_settings
  ADD COLUMN IF NOT EXISTS phone TEXT DEFAULT '(604) 279-0335',
  ADD COLUMN IF NOT EXISTS tax_rate DECIMAL(5, 4) NOT NULL DEFAULT 0.13,
  ADD COLUMN IF NOT EXISTS pause_until TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS sold_out_item_ids JSONB NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS tax DECIMAL(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total DECIMAL(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS admin_dismissed BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE restaurant_settings SET closing_time = '21:00:00' WHERE closing_time = '20:45:00';
